project_name: golang-rcs
builds:
  -
    id: dbxconvert
    binary: dbxconvert
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: NA
    homepage: https://github.com/csima/dbxconvert
    maintainer: Caleb Sima <csima@github.com>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
